apiVersion: v1
kind: Service
metadata:
  name: {{ include "exporter.fullname" . }}
  namespace: {{ .Values.namespace | default $.Release.Namespace }}
  labels:
    {{- include "exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- .Values.exporter.ports | toYaml | nindent 2 }}
  selector:
    {{- include "exporter.selectorLabels" . | nindent 4 }}
